# MCDealer 2 Config
language: en-US #en-US or de-DE (ONLY INTERNAL LANGUAGE)
data:
  interval: 10m #(s = seconds, m = minute, h = hour)
web:
  port: 8089
  use-internal-website: true
debug-mode: true
# Don't change anything below!
config-version: 3

