name: MCDealer2
version: '1.0'
main: org.cptgummiball.mcdealer2.MCDealer2
api-version: '1.21'
authors: [ cptgummiball ]
commands:
  mcdealer:
    description: Manage your shops and reload the plugin
    usage: /mcdealer [reload|hideshop|showshop]
permissions:
  mcdealer.hideshop:
    description: Allows hiding your shops with /mcdealer hideshop.
    default: true
  mcdealer.showshop:
    description: Allows showing your shops with /mcdealer showshop.
    default: true
  mcdealer.admin:
    description: Allows executing admin commands such as /mcdealer reload.
    default: op